import { defineField, defineType } from 'sanity'

export const pageContentType = defineType({
  name: 'pageContent',
  title: 'Pagina Inhoud',
  type: 'document',
  fields: [
    // ── Hero Sectie ──────────────────────────────────
    defineField({
      name: 'heroSubtitle_nl',
      title: 'Hero — Ondertitel (NL)',
      type: 'string',
      group: 'hero',
    }),
    defineField({
      name: 'heroSubtitle_fr',
      title: 'Hero — Sous-titre (FR)',
      type: 'string',
      group: 'hero',
    }),
    defineField({
      name: 'heroSubtitle_en',
      title: 'Hero — Subtitle (EN)',
      type: 'string',
      group: 'hero',
    }),
    defineField({
      name: 'heroTitle_nl',
      title: 'Hero — Titel (NL)',
      type: 'string',
      group: 'hero',
    }),
    defineField({
      name: 'heroTitle_fr',
      title: 'Hero — Titre (FR)',
      type: 'string',
      group: 'hero',
    }),
    defineField({
      name: 'heroTitle_en',
      title: 'Hero — Title (EN)',
      type: 'string',
      group: 'hero',
    }),
    defineField({
      name: 'heroTitleAccent_nl',
      title: 'Hero — Titel Accent (NL)',
      type: 'string',
      description: 'Gebruik \\n voor een nieuwe regel.',
      group: 'hero',
    }),
    defineField({
      name: 'heroTitleAccent_fr',
      title: 'Hero — Titre Accent (FR)',
      type: 'string',
      group: 'hero',
    }),
    defineField({
      name: 'heroTitleAccent_en',
      title: 'Hero — Title Accent (EN)',
      type: 'string',
      group: 'hero',
    }),
    defineField({
      name: 'heroDescription_nl',
      title: 'Hero — Beschrijving (NL)',
      type: 'text',
      rows: 3,
      group: 'hero',
    }),
    defineField({
      name: 'heroDescription_fr',
      title: 'Hero — Description (FR)',
      type: 'text',
      rows: 3,
      group: 'hero',
    }),
    defineField({
      name: 'heroDescription_en',
      title: 'Hero — Description (EN)',
      type: 'text',
      rows: 3,
      group: 'hero',
    }),
    defineField({
      name: 'heroCta_nl',
      title: 'Hero — Knoptekst primair (NL)',
      type: 'string',
      group: 'hero',
    }),
    defineField({
      name: 'heroCta_fr',
      title: 'Hero — Bouton primaire (FR)',
      type: 'string',
      group: 'hero',
    }),
    defineField({
      name: 'heroCta_en',
      title: 'Hero — Primary button (EN)',
      type: 'string',
      group: 'hero',
    }),
    defineField({
      name: 'heroCtaSecondary_nl',
      title: 'Hero — Knoptekst secundair (NL)',
      type: 'string',
      group: 'hero',
    }),
    defineField({
      name: 'heroCtaSecondary_fr',
      title: 'Hero — Bouton secondaire (FR)',
      type: 'string',
      group: 'hero',
    }),
    defineField({
      name: 'heroCtaSecondary_en',
      title: 'Hero — Secondary button (EN)',
      type: 'string',
      group: 'hero',
    }),
    defineField({
      name: 'heroStatYears',
      title: 'Hero — Statistiek (jaren)',
      type: 'string',
      description: 'Bijv. "20+"',
      group: 'hero',
    }),
    defineField({
      name: 'heroStatYearsLabel_nl',
      title: 'Hero — Statistiek label jaren (NL)',
      type: 'string',
      group: 'hero',
    }),
    defineField({
      name: 'heroStatYearsLabel_fr',
      title: 'Hero — Label statistique années (FR)',
      type: 'string',
      group: 'hero',
    }),
    defineField({
      name: 'heroStatYearsLabel_en',
      title: 'Hero — Stat years label (EN)',
      type: 'string',
      group: 'hero',
    }),
    defineField({
      name: 'heroStatSpecialists',
      title: 'Hero — Statistiek (specialisten)',
      type: 'string',
      description: 'Bijv. "2"',
      group: 'hero',
    }),
    defineField({
      name: 'heroStatSpecialistsLabel_nl',
      title: 'Hero — Statistiek label specialisten (NL)',
      type: 'string',
      group: 'hero',
    }),
    defineField({
      name: 'heroStatSpecialistsLabel_fr',
      title: 'Hero — Label statistique spécialistes (FR)',
      type: 'string',
      group: 'hero',
    }),
    defineField({
      name: 'heroStatSpecialistsLabel_en',
      title: 'Hero — Stat specialists label (EN)',
      type: 'string',
      group: 'hero',
    }),

    // ── Sectie Headers ───────────────────────────────
    // Specialisten
    defineField({
      name: 'specialistsLabel_nl',
      title: 'Specialisten — Label (NL)',
      type: 'string',
      group: 'sections',
    }),
    defineField({
      name: 'specialistsLabel_fr',
      title: 'Spécialistes — Label (FR)',
      type: 'string',
      group: 'sections',
    }),
    defineField({
      name: 'specialistsLabel_en',
      title: 'Specialists — Label (EN)',
      type: 'string',
      group: 'sections',
    }),
    defineField({
      name: 'specialistsTitle_nl',
      title: 'Specialisten — Titel (NL)',
      type: 'string',
      group: 'sections',
    }),
    defineField({
      name: 'specialistsTitle_fr',
      title: 'Spécialistes — Titre (FR)',
      type: 'string',
      group: 'sections',
    }),
    defineField({
      name: 'specialistsTitle_en',
      title: 'Specialists — Title (EN)',
      type: 'string',
      group: 'sections',
    }),
    defineField({
      name: 'specialistsDescription_nl',
      title: 'Specialisten — Beschrijving (NL)',
      type: 'text',
      rows: 3,
      group: 'sections',
    }),
    defineField({
      name: 'specialistsDescription_fr',
      title: 'Spécialistes — Description (FR)',
      type: 'text',
      rows: 3,
      group: 'sections',
    }),
    defineField({
      name: 'specialistsDescription_en',
      title: 'Specialists — Description (EN)',
      type: 'text',
      rows: 3,
      group: 'sections',
    }),
    // Expertise
    defineField({
      name: 'expertiseLabel_nl',
      title: 'Expertise — Label (NL)',
      type: 'string',
      group: 'sections',
    }),
    defineField({
      name: 'expertiseLabel_fr',
      title: 'Expertise — Label (FR)',
      type: 'string',
      group: 'sections',
    }),
    defineField({
      name: 'expertiseLabel_en',
      title: 'Expertise — Label (EN)',
      type: 'string',
      group: 'sections',
    }),
    defineField({
      name: 'expertiseTitle_nl',
      title: 'Expertise — Titel (NL)',
      type: 'string',
      group: 'sections',
    }),
    defineField({
      name: 'expertiseTitle_fr',
      title: 'Expertise — Titre (FR)',
      type: 'string',
      group: 'sections',
    }),
    defineField({
      name: 'expertiseTitle_en',
      title: 'Expertise — Title (EN)',
      type: 'string',
      group: 'sections',
    }),
    defineField({
      name: 'expertiseDescription_nl',
      title: 'Expertise — Beschrijving (NL)',
      type: 'text',
      rows: 3,
      group: 'sections',
    }),
    defineField({
      name: 'expertiseDescription_fr',
      title: 'Expertise — Description (FR)',
      type: 'text',
      rows: 3,
      group: 'sections',
    }),
    defineField({
      name: 'expertiseDescription_en',
      title: 'Expertise — Description (EN)',
      type: 'text',
      rows: 3,
      group: 'sections',
    }),
    // FAQ
    defineField({
      name: 'faqTitle_nl',
      title: 'FAQ — Titel (NL)',
      type: 'string',
      group: 'sections',
    }),
    defineField({
      name: 'faqTitle_fr',
      title: 'FAQ — Titre (FR)',
      type: 'string',
      group: 'sections',
    }),
    defineField({
      name: 'faqTitle_en',
      title: 'FAQ — Title (EN)',
      type: 'string',
      group: 'sections',
    }),
    // Praktische Informatie
    defineField({
      name: 'practicalInfoLabel_nl',
      title: 'Praktisch — Label (NL)',
      type: 'string',
      group: 'sections',
    }),
    defineField({
      name: 'practicalInfoLabel_fr',
      title: 'Pratique — Label (FR)',
      type: 'string',
      group: 'sections',
    }),
    defineField({
      name: 'practicalInfoLabel_en',
      title: 'Practical — Label (EN)',
      type: 'string',
      group: 'sections',
    }),
    defineField({
      name: 'practicalInfoTitle_nl',
      title: 'Praktisch — Titel (NL)',
      type: 'string',
      group: 'sections',
    }),
    defineField({
      name: 'practicalInfoTitle_fr',
      title: 'Pratique — Titre (FR)',
      type: 'string',
      group: 'sections',
    }),
    defineField({
      name: 'practicalInfoTitle_en',
      title: 'Practical — Title (EN)',
      type: 'string',
      group: 'sections',
    }),
  ],
  groups: [
    { name: 'hero', title: 'Hero Sectie', default: true },
    { name: 'sections', title: 'Sectie Koppen' },
  ],
  preview: {
    prepare() {
      return { title: 'Pagina Inhoud' }
    },
  },
})
